# Izinkan akses tanpa user/pass
allow_anonymous true

# Jalur untuk Python & Explorer (TCP)
listener 1883 0.0.0.0

# Jalur untuk Web Dashboard (Websockets)
listener 9001 0.0.0.0
protocol websockets

# Tambahkan ini agar data langsung disalurkan tanpa delay
socket_domain ipv4